name: Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

      - name: Deploy Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} "
            docker pull kuberneks4/weatherbot:latest &&
            docker stop weather || true &&
            docker rm weather || true &&
            docker run -d --name weather kuberneks4/weatherbot:latest Lagos
          "
